package RockPaperScissors;


/**
* RockPaperScissors/GameControllerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RockPaperScissors.idl
* Thursday, April 2, 2015 7:44:39 PM IST
*/

public interface GameControllerOperations 
{

  //creates a new instance of game and returns an identifier as well as the ID for the game in the form on an Any
  String NewGame (org.omg.CORBA.AnyHolder gameIdAny);
  boolean gameIsReadySynchronous (int GameID);

  //client passes in the ID it received from the Any and check if they have been matched with an opponent
  void gameIsReady (RockPaperScissors.GUICallback callback, int GameID);

  //takes the user's choice and their identifier and returns the winner of the game - synchronous blocking call - used by CLI client
  String SynchronousResult (int GameID, int move, String userNumber);

  //asynchronous call which uses callbacks - used by GUI client
  void Result (RockPaperScissors.GUICallback callback, int GameID, int move, String userNumber);
} // interface GameControllerOperations
