package RockPaperScissors;

/**
* RockPaperScissors/GameControllerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RockPaperScissors.idl
* Thursday, April 2, 2015 7:44:39 PM IST
*/

public final class GameControllerHolder implements org.omg.CORBA.portable.Streamable
{
  public RockPaperScissors.GameController value = null;

  public GameControllerHolder ()
  {
  }

  public GameControllerHolder (RockPaperScissors.GameController initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RockPaperScissors.GameControllerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RockPaperScissors.GameControllerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RockPaperScissors.GameControllerHelper.type ();
  }

}
