package RockPaperScissors;


/**
* RockPaperScissors/GUICallback_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RockPaperScissors.idl
* Thursday, April 2, 2015 7:44:39 PM IST
*/

public class GUICallback_Tie extends _GUICallbackImplBase
{

  // Constructors
  public GUICallback_Tie ()
  {
  }

  public GUICallback_Tie (RockPaperScissors.GUICallbackOperations impl)
  {
    super ();
    _impl = impl;
  }

  public void callBack (String winner)
  {
    _impl.callBack(winner);
  } // callBack

  private RockPaperScissors.GUICallbackOperations _impl;

} // class GUICallback_Tie
