package RockPaperScissors;


/**
* RockPaperScissors/GUICallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RockPaperScissors.idl
* Thursday, April 2, 2015 7:44:39 PM IST
*/

public interface GUICallbackOperations 
{
  void callBack (String winner);
} // interface GUICallbackOperations
