package RockPaperScissors;

/**
* RockPaperScissors/GUICallbackHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RockPaperScissors.idl
* Thursday, April 2, 2015 7:44:39 PM IST
*/

public final class GUICallbackHolder implements org.omg.CORBA.portable.Streamable
{
  public RockPaperScissors.GUICallback value = null;

  public GUICallbackHolder ()
  {
  }

  public GUICallbackHolder (RockPaperScissors.GUICallback initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RockPaperScissors.GUICallbackHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RockPaperScissors.GUICallbackHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RockPaperScissors.GUICallbackHelper.type ();
  }

}
